# Generated by Django 2.0.1 on 2018-02-23 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('continents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(choices=[('colombia', 'CO'), ('mexico', 'MX'), ('estados unidos', 'USA'), ('argentina', 'AR')], max_length=3)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='continents.Continent')),
            ],
        ),
    ]
