# Generated by Django 2.0.1 on 2018-03-06 15:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
